### PR TITLE
Features/outputlib based on pandas uvchik

### PR DESCRIPTION
**Pull request by uvchik**
I started to make bus_plot to a default plot function as discussed in #36. I think stackplot is a good example to test if bus_plot can be used in higher plot functions.

The following comments are connected to the commits use the link in the header of the comment.

### CODE REVIEW

**Comment by uvchik** [comment]
Please merge (partly merge) if you agree.

**Comment by simonhilpert** [comment]
Can we soon merge outputlib into dev for use in other feature branches as well?

**Comment by uvchik** [comment]
I think we should clarify the last things about the api (optional and obligate parameters) before we merge it into the master but you can merge this branch into your feature branch to use the plotting class.

I would like to make `date_to` and `date_from` an optional parameter and plot the whole timeset if no limit is given. What so you think?

**Comment by ckaldemeyer** [comment]
I agree!

**Comment by ckaldemeyer** [comment]
Oh, I have just read my mails and saw your pull request! Meanwhile I have removed some bugs and added some feature. See #36 or repo for changes.

Maybe a short web conference tomorrow morning would be faster to clear all remaining questions!

**Pull request merged**
