### PR TITLE
add a whats new section the documentation

### PR DESCRIPTION
**Pull request by uvchik**
_Sorry the last pull request was a mistake because I want to merge this into dev and not into master branch._

I would like to add a "what's new" section to the documentation. I got the idea from the pvlib.

Now everybody can add a line to the file of the next version, if something is added, changed, enhanced,...

@oemof/oemof-main : What do you all think about it?

### CODE REVIEW

**Comment by uvchik** [comment]
I would like to merge this tonight.

No comment might mean, that it is okay. 

@oemof/oemof-main : Please use the "whats new" section if you enhanced something, fixed a bug, extended the documentation or ...

**Comment by simonhilpert** [comment]
why do you want to merge the whatsnewbranch? I thought we are going to do the next release late december until then we can add infos about new stuff?

**Comment by uvchik** [comment]
Right. But by now we do not have the section. I want to add the section, so that everybody can add new stuff directly until December and not two days before the release. Than we will forget half of the things we've done. That's why I merge it into the dev branch. 

I just wanted everybody to know about this, so that everybody will fill the December sheet.

**Comment by simonhilpert** [comment]
Ok, but we will work on the feature branch and merge it once again for the release?

**Comment by uvchik** [comment]
No. I will merge it into the dev branch and delete the feature-branch.

Every time you merge a feature or a bug-fix into the dev branch you should add to the whatsnew file what you have done. you can do that in your feature/bug-fix branch and merge it together with the code. 

I would say in the long run every merge has to contain the code, the according docs, the according tests and the whatsnew entry. But this a new issue but not this year any more.

**Pull request merged**
