### PR TITLE
Replace print by logging.info

### PR DESCRIPTION
**Pull request by uvchik**
Therefore we have to be sure that  at least a basic logger is defined otherwise there won't appear anything on the screen. So I defined a very basic logger to see the message on the screen.

It is still possible to use the default oemof logger described  in issue #28.

The advantage is that you can see the message on the screen and(!) in the file. Furthermore it is configurable so that you can decide what level you want to see, and what level you want to log in a file.

 See the following link for more information: https://docs.python.org/3/howto/logging.html

@oemof/oemof-main : Is it okay to merge it?

### CODE REVIEW

**Comment by caro-rli** [comment]
I'm ok. Now I can't also see any logging from the solver, can I?

**Comment by simonhilpert** [comment]
do you mean from solph module or solver information? You can print out solver information in 
the console by setting verbose=True in the simulation object. 

logging in solph is something that needs to be coded...

**Comment by uvchik** [comment]
I know that I can use the verbose level to print out the solver message. I do not like the `print` command because everything is gone if I run anything else. With the logging command I can display the information and write them to a file. I would like to change the behaviour of the verbose mode. I would like `verbose=True` to lift up the message to a higher logging level.

`verbose=False`: logging.debug('Solver output.....')
`verbose=True`: logging.info('Solver output.....')

You can see the changes on commit b480241.

I am open for other suggestions.

**Comment by simonhilpert** [comment]
I think thats good.

**Comment by simonhilpert** [comment]
ok i will push some changes in a few minutes

**Comment by simonhilpert** [comment]
Ok I pushed.

**Comment by uvchik** [comment]
@simonhilpert wrote:
> Do we merge use logging for the next release? I have made some changes on the branch (that are actually not to be placed there, and I do not know why I did this - but I did)

I would merge it for the January release if there are no objections.

**Comment by ckaldemeyer** [comment]
(y) Sounds good as we also want to use it in renpass-gis.

**Comment by gnn** [comment]
Sounds good to me. :+1:

**Pull request merged**
